kind: ConfigMap
apiVersion: v1
metadata:
  name: qm1-cm
  namespace: mq
data:
  config.mqsc: |-
    DEFINE QL(APPQ)
    DEFINE CHANNEL(QM1CHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(QM1CHL) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
  qm.ini: |-
    Channels:
      MQIBindType=FASTPATH
---
kind: Secret
apiVersion: v1
metadata:
  name: qm1-cert
  namespace: mq
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvakNDQVlvQ0NRQ2cvMVNpMWJIZnJ6QU5CZ2txaGtpRzl3MEJBUXNGQURBVE1SRXdEd1lEVlFRRERBaHQKY1hObGNuWmxjakFlRncweU1URXlNVFl4TkRRek1EbGFGdzB6TVRFeU1UUXhORFF6TURsYU1CTXhFVEFQQmdOVgpCQU1NQ0cxeGMyVnlkbVZ5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyRU5nCnBJZ28wUytpZzlZQnJEMVZTUUpNTnpDWkp4cUVuelVTNUtvSVdDL3M4eWRpOVdOSS9UZG5ubUNPZHk0TzZ6SnAKRm0zRVczYWh5WXNFeVV5Q2hlbUhqSGMySDdGQkp5SzdLdXRmUXVoWWtTWlJ6a3k3SDlxekk4ZENqd2x3NTljQwpEajR0MVFYQzBrbmd4eFpLSlhvaWR6Tmk4RlBxLzI4QTgyNVBuK28zS0JQL0pJSHJRTmkrMGFLUzJIYVJDNVgwCmIybllzVWxUSFdpSHgrSVJsNDhBajFwOENncXhjcHA3bjlKd0swODEwYytkNzdOTDVmeDB4bFV1UTQwOEEyRlMKa2ZCR3YrOWdoQ0FEeHNlVlRpWml3bzczK0RnNjFOUVVFVWkydDc1RDBuaDE3RzZXYlRSL1YrOG1ZZXZJZFladQpvcXJ5M3NtOUthclF0SGNORndJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUM2U2J4UVlRM2g4SVpxCmdxT09pbG5QalcvVFdoS0E4enczaTFsN1ZPdlAxYWRsRXVZUDc4NldFL0JHYUtxdk42WkZZczFCWElBLzVHeUoKK2NKeWxmQksyTnRFanFKTEYzYklqbmR2N1lLSHNUMStBVituVTdDZGEvd0o4aXY5UkFqT3luNXYwOHhvU1FBSQpEb3ZtT29wS212QzRxY3BMVm0yczlFWFRKenVBWkRYNmh4ZzZ1MzRsZ0tQb3hRRWhYTm4xVXVnTjlKNFZKd3FPCmM0RFZxVUo2UmFiUzhLbWw4WnZJenEyblg1c1hGaWJPZm11S2NFRmxBMjBBaVkydVI0NGNGdENyak0vSjhmVEwKTDRyNVhYVFZiOUZXRmF6OTVseWMvWWJveTJTUENudWxlVWpETDZ5aVExdVhJRkUrcjMvZG5uWjdwNUhQZnJZSgo0ZnQ0Y1V1RAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFlRMkNraUNqUkw2S0QKMWdHc1BWVkpBa3czTUprbkdvU2ZOUkxrcWdoWUwrenpKMkwxWTBqOU4yZWVZSTUzTGc3ck1ta1diY1JiZHFISgppd1RKVElLRjZZZU1kellmc1VFbklyc3E2MTlDNkZpUkpsSE9UTHNmMnJNangwS1BDWERuMXdJT1BpM1ZCY0xTClNlREhGa29sZWlKM00yTHdVK3IvYndEemJrK2Y2amNvRS84a2dldEEyTDdSb3BMWWRwRUxsZlJ2YWRpeFNWTWQKYUlmSDRoR1hqd0NQV253S0NyRnltbnVmMG5BclR6WFJ6NTN2czB2bC9IVEdWUzVEalR3RFlWS1I4RWEvNzJDRQpJQVBHeDVWT0ptTENqdmY0T0RyVTFCUVJTTGEzdmtQU2VIWHNicFp0Tkg5WDd5Wmg2OGgxaG02aXF2TGV5YjBwCnF0QzBkdzBYQWdNQkFBRUNnZ0VBRUVxYkdDbnRzVHgrYUtJUmhERW1vSlpjdVhlZXdmUmNjMFhqUTNpUG9sMFIKNDR0ZkNBOVBxMHVtTWFjaWRGWHk1OExuYWJvaEphYTlMMXFhcExOdnpiaTI3bHo0cGRDTGtQQXIyMkxaelVlRgpqSUd2ZmZRSDBMRi85ejBHaFpIM2dHK1JCeE9tRGpzZDN3dVR0RXU0a0RRd0xueWZnbTAvOGJnaUFUU1pLUG12CmJSSXV4UmtrdkZtNnZtMnBZa0JOWTJ4QjUwakgra3FaOFZwWWJsd2V5c0J4bUtwaVlIb282T20zV2tjYjRramQKNlhnbjRuaVUxZDhtVTdRQ1pvSFMvQ2dZM0V3S2FVSWovUnJNOW90ZVZ2UVZPUWZNakdYS0JvcExkT1ZORFdCZAp5U2psWEF1UzhYcWd4QjdxYTBkZUw1VkZBVXY5ZzNjcFNURzUxazRvb1FLQmdRRDFHeEp2WVpTNXZBeEptL253Ck9NU2ZQdENQaHFmY1lnc3A4cE5JRUExSkRHMW1nMGlMa3VhcEVPRGh1Q3prRVB0NUlNdXljay9neGVaTTVCbVoKYmhIa3RRTVIwWTJaOWVncHdncXB3dVp3d01ydUt3Z3lXczVWaWdvS3Z2bTJlVkptcC9lU3JPU3Q5ZnNOZXVZOQo1d0RiTHhrSFQ3b2xZbE1vVjdYU0dDZS9od0tCZ1FEaDRCOFRDaUFzZytTZDJyMGdoenlSTmhxRlBOUVJuaFRzCjNUN1ZZZFJwbTB3YWUzTzdoOElDaEw3VEdYUXNyQm1NSTZqWTE0bUR5TGJrRVRIR2xocjQxSTkxL0FXZEFwK1oKSEhtSFhuTTRQV0Noc3N6WS8zTnFMTnBzRjUrSUt3N3ZMd2Y5bDc2a3ZoUUx1YS96bmxnMXFqaXdxc2ZMNkMzeQptcnVLR0RBSjhRS0JnR0FXU05mWlRWQ3k0NjVIczJmMUdUL0VoRVovNTNhQ0NSWmN2bGhWMHA5OGU3YmdhS1F1CjVyWUlvK0JaTDJBSk9FeDRDdUxkNVdxY3FuZ2lROWJlUzYxNU9NYlhlOGVMbTRRalNjTGJZVE42b1JOVlUxVksKTy9GVXVETVdReGJCNFFmVmVUekxBcXNmNzFlTmdvMXA3ZS8vT3JTZkVMNXZHV0tMWUFBSThDd3BBb0dCQUoyNwpDVmdkV1F4YzZoZkZlUTZ2QVgrUjNZRXZVaFFmWlJObkNJcXZyMG96OVRnRS8zTjBRT25MVXdwTkd4QmErZGdmCnlyZnFBNUJ3YUM3cFJ1NGJRaWlESHM5UU40ZEdIcmNuNkVHOGxnOHU1VHpsaENFQWVkTXFFVGtzWWU0UHkzVUIKVGI0cjZpaFd4OTdNUTIrSElxZ08vMWwzV09BdWVXK1IxK1orTDRXeEFvR0JBS09yREdUeDVaK1FVNVhCaDROMQpVckJxSFQ4UDBYQjJXSjVCTFZKbDdmb1dZTmxrdTl1N0xvbzNrSkhhSjQ5SWxnQ0ZHSXVqNk9td25tSVJiL25kCkt4UEt6SksvODFWNlpxc0dlMElHU2wreHJtNG9YVnhPelNFMFJNaUNUWlRId0hvelFLZGlqYmxHdnhYdyszR1QKbzRlR055ZzZhZFhyRzRSaE9STjQ5VmY5Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  mqclient.crt: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRE5RRU9xZGJuRVNlZGkKRHU5NDNTUVhPeGNSTUNESHEvZ3cwS1FUdzUxWndFWThMbzk5Sk80U1JOYVA5U3FndUMvTStIV3gxN3ZHS1BEZwowUkwvb2xxR1dmdFd0SWJSWGRBRUtsVTk0d2lKcHdOeno2aVRjZmlsUS91NVJxYS91SmE1eHdkRTNuMGVROWNNCmlUUS9OazhzaG9uYjJXTU9nUllOQXFFeVU0alRrWTVmak91Q2YzVER3RlBKaHM5ODlGYURrQ3NWRVNOZlFjMG4KOStQaDFXaGlRUGlwa05jZ0ZHWDNKSFBScGNKQVRMNXVMWWswbGMySmlDVXBuLytyR2hLVUtUMWNrR1FKK2NMVgpCTTNjdVFXTnRnWmI5K2YvbGNka09UUWdRcFMxc2t3YmlHVHVqcXF6ZVRRWVAwblFobkNxQ0czUHAvbGtFREpqCnhqTlBwb1NmQWdNQkFBRUNnZ0VBVEZrTlVvajhFdkhTcWYwWVF3TXZlNXkxVmVWckxCcmg5WGFHc2Z0ZnVwVDEKQzBuZWdoU01vaXNORFB1TFljRmh0b0x0ZEx2azB5OURlcjBLcmlCOFArR1V4b25jWkdEYkVkR1ZaN0hkNlNaQQorSUZVR1pTWmd4QW93S0J4UW51dFJXbXRZSWJLVDhtNFlxZGUwZXlud3M1QTFaQ2xjaTIrUUJTc1ZZWVJMWEVhCmhrdXRhN2VIcGFUUFRneWVQOXFXQ0JVYXZ2NEV0ZVdRdjVvQU9pQm1JUHVqSkljVnFGNWtENVByNVREL0xFcnIKbWhVdFkzVXJEWXVTUDB3RGY2V1dzWTRGcnVpZ29ZR0V0TERBaWRkZFltOEtqUzczdzgxZkMwdG9UMVZOQS9PeQpWYjdvZFQwSHFXWkU3cWtRNnpYYWNGaW9SZGtaaWMzKy9GWjIvQWF5Y1FLQmdRRHpmcU8xUzBkSEQybjB2RksyClZwdS9JVGNtK2x2b2JlMWNCLzhoNHdwUXBzUVhZcUY5SldnNElyV1ZoNDZKZXBZSms1RDNnYkFHRXBHNmpSUVIKWmFrTGZpTkVncFI5bmw4QkNnRUxOVTJCeUxkdkRGTUtWSUd5VTFscFNSelZRaWVyVnNIclROMVRUdXpOdXpSSQpSTmxUZzRZQXluYXpVMzZ5M3RwQ2VZYWZhd0tCZ1FEWHl0QnVoNll5VUF1aVlHLzVMZEJ1M1AyYXNRaytXSk5SCkZYRUtpV2RPazVYZkozTWo5MlZLZWtUejZReXlGeWtid1lGZ1cyL29VNER6ajFxeFF5N05sdzR4SzZqY1lUVHAKMTdvWGIxMStQM29UWHVyN3diL1BxcUVLZUdpNHA0UHMySUV2Z3hqdi9pUUk1SEpIcTVJcjJhRHZvVG9aNkdxWAoxaSt1VzdSQW5RS0JnQ3dOb0c2L2RPRGRZQTBnT1ZLMTdxMnd3N3F3bHdwQlFTMWlZUDF2aDBFNk9zWUVXVFU4CkhGUHpxNmluQXRuS3JQU0VsempBWk9sa1dLdEl0UFhFejhXOWg0SHdvZzdzSlVJWjNrQjUzMUQ0MEg4dDJxUkcKejhSRW9pdVRSNzBwbitXMjU1UzdybHRSTHpTMWh1c0FVZFZ6T1Q1Ull4SmtxOHFPMlN3bnNueUxBb0dBZmNVNgppRUZOajJOeDlIaktxbXVXWVJjeVJGZk1zR2JGcmV1V1QvTFhvRWVLZ1Y2bjBCMmdEckdHd0xaaTdPVnMwejJNCkgxSUx2bGYwLzMvYzl4WFdFSU5yQlNPU0xxZ0ZSQW0wNzNXOEF4b1NGM29wOFFQeXZLR1JiTjNUQTFTM0luTHAKa0h5VEswVnZVVE44bStNV3RiSUpCOEZyY0xBeWVENmcyYm1mTEUwQ2dZQkRjQU9aUkFjc0JsWHFnYnpWWGEvbgpuRmd5TmtoUjcybFhpTXJ1dWdKak1JYWhmYlgxVXBaUndrbmJNZFVFcFM1dld0TmZMcVJsZDNTelF4ZTUxQzd6CmlZYkp6cUhlM2pJRWxBTE5rOXBOeUZSVUFlam94czdmYzF5b1U0TmtmNlU2NEI0bmlOVTlJNko3eWFlckxTNVEKMGxKeGJGcUw4dy85ekNJK1UvTm5WUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: Opaque
---
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
  namespace: mq
spec:
  version: 9.2.3.0-r1
  license:
    accept: true
    license: L-RJON-BZFQU2
    use: NonProduction
  pki:
    keys:
    - name: default
      secret:
        secretName: qm1-cert
        items:
          - tls.key
          - tls.crt
  web:
    enabled: true
  queueManager:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    name: QM1
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    mqsc:
      - configMap:
          name: qm1-cm
          items:
            - config.mqsc
    storage:
      defaultClass: ibmc-block-gold
      persistedData:
        enabled: true
        size: 2Gi
        type: persistent-claim
      queueManager:
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sni-qm1chl-ibm-mq-qm
  namespace: mq
spec:
  host: qm1chl.chl.mq.ibm.com
  to:
    kind: Service
    name: qm1-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
  wildcardPolicy: None
